### ISSUE TITLE
Add an example for @ mentions including an autocomplete

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/draft-js-plugin-editor#2]
I think for a first example a static list of users to auto complete should be good enough.

Since names contain of multiple parts making them [segmented](https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#segmented) sounds like a good idea. That's the Facebook behaviour where it autocompletes to the full-name, but people are still able to remove parts without removing the entity.

In here you have basic implementation of @ mentions. Extending it with a autocomplete will be tricky, but definitly doable. https://github.com/facebook/draft-js/blob/master/examples/tweet/tweet.html

**Comment by mjrussell** [comment]
I actually got an example of this working yesterday and was looking for a place to put it. 

This seems about as good as any :smile:. I need to do some refactoring and might want some ideas on improving the dropdown but it should be a good starting point. I'll try to get a PR in the next few days.

Removing the parts is just the difference between the MUTABLE vs IMMUTABLE on the entity. I was thinking a fun example might be a static github issue list because it could do both search by number and search by name after you type `#`. A similar one could be twitter handle and by full name.

**Comment by nikgraf** [comment]
@mjrussell wow, amazing! Do you have time to do some pair programming tonight (SF time)? I was thinking about doing a release/launch tomorrow of the plugin system. Having yours in would be really cool.

**Comment by mjrussell** [comment]
@nikgraf replied on the draftJS slack to coordinate :smile:
